# Background & fottreground
background #462083
foreground #14C2DD


# Cursor
cursor #F25FAF

# Selection
selection_background #33111E
selection_foreground #14C2DD

# Light → Dark Blue Shades
color0  #e6f2ff   # very light blue
color1  #cce4ff   # soft light blue
color2  #99c9ff   # light sky blue
color3  #66adff   # sky blue
color4  #338fff   # bright blue
color5  #0073e6   # strong blue
color6  #005bb5   # deep blue
color7  #003d80   # very dark blue

# Bright colors
color8  #1a1f26   # bright black (alt bg)
color9  #ff6aa0   # bright pink
color10 #2bffb5   # bright green
color11 #ffe082   # bright yellow
color12 #33cfff   # bright blue
color13 #d5a6ff   # bright purple
color14 #5dfdff   # bright cyan
color15 #ffffff   # pure white
