# Background & foreground
background #915836
foreground #000000


# Cursor
cursor #F9CFB7

# Selection
selection_background #8E4453
selection_foreground #14C2DD

# cold colours
color0 #FFD700
color1 #FFDE33
color2 #FFE566
color3 #FFEC99
color4 #FFF2B3
color5 #FFF7CC
color6 #FFFBE6
color7 #B3DCFF

# warm colours
color8 #FFD700
color9 #ff8c42
color10 #ffb347
color11 #ffd166
color12 #ff9e64
color13 #ffcc80
color14 #ffe29a
color15 #fff3d1
