# Background & fottreground
background #250E41
foreground #F25FAF


# Cursor
cursor #F25FAF

# Selection
selection_background #592041
selection_foreground #CF6898

color0  #0a0f1f   # very dark blue
color12 #33cfff   # bright blue
color13 #d5a6ff   # bright purple
color3  #1f4f8b   # mid blue
color4  #2f6fd6   # bright blue
color5  #3f8cff   # neon blue
color6  #5fb3ff   # light neon blue
color7  #cfe8ff   # pale blue (foreground)

# Bright colors
color8  #1a1f26   # bright black (alt bg)
color9  #ff6aa0   # bright pink
color10 #2bffb5   # bright green
color11 #ffe082   # bright yellow
color12 #33cfff   # bright blue
color13 #d5a6ff   # bright purple
color14 #5dfdff   # bright cyan
color15 #ffffff   # pure white
