# Background & fottreground
background #33111E
foreground #FB6C50


# Cursor
cursor #F9CFB7

# Selection
selection_background #8E4453
selection_foreground #14C2DD

color0  #1a0f0a   # very dark burnt base
color1  #3a1f12   # deep burnt orange
color2  #5a2e1a   # earthy orange
color3  #7a3f22   # warm clay
color4  #a6532a   # rich orange
color5  #d96a2f   # bright orange
color6  #ff8c42   # glowing orange
color7  #ffd1a3   # soft highlight orange

color8  #140d0a   # dark soil
color9  #2e1b12   # deep brown
color10 #4a2c1a   # wood brown
color11 #6b3e24   # warm bark
color12 #8c5230   # rich earthy brown
color13 #b06a3a   # sunlit wood
color14 #d49a5a   # warm sand
color15 #f2d2a2   # soft warm light
