# Background & fottreground
background #293436
foreground #D7B861


# Cursor
cursor #DD8E6B

# Selection
selection_background #4B7396
selection_foreground #ACB346

color0  #0f1a12   # deep forest bg
color1  #1b2b1f   # dark moss
color2  #244d2c   # forest green
color3  #2f6b3a   # leaf green
color4  #3f8f4f   # fresh green
color5  #5faa6f   # soft green
color6  #7bcf8f   # light green
color7  #cfead6   # pale green (foreground)

# Bright colors
color8  #1a140f   # dark soil
color9  #5c3d2e   # bark brown
color10 #7a5230   # wood brown
color11 #a4713a   # dry grass
color12 #c89b5a   # warm sand
color13 #e0b96a   # soft sunlight
color14 #f2d48a   # light sunlight
color15 #fff3c4   # warm highlight
