# Background & fottreground
background #000000
foreground #FFFFFF


# Cursor
cursor #FFFFFF

# Selection
selection_background #636363
selection_foreground #000000

# cold colours
color0 #000000
color1 #1C1C1C
color2 #383838
color3 #555555
color4 #717171
color5 #8D8D8D
color6 #AAAAAA
color7 #C6C6C6
# warm colours
color8 #C6C6C6
color9 #D2D2D2
color10 #DEDEDE
color11 #EAEAEA
color12 #F0F0F0
color13 #F5F5F5
color14 #FAFAFA
color15 #FFFFFF
